# Site settings
title: Sri Lanka Backpacking
email: dev@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Sri Lanka Backpacking. This is a personal blog. Max and Henriette
  travelling in Sri Lanka februar 24th till march 16th.
permalink: ':title/'
baseurl: "/srilanka" # the subpath of your site, e.g. /blog
url: "https://mxklb.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# Author settings
author: Xam Blak # add your name
author-pic: avatar.jpg
about-author: My name is Xam Blak. I’m a hobby backpacker & blogger.

# Contact links
email: mxklb@protonmail.com # Add your Email address
phone: # Add your Phone number
website: www.xamblak.de # Add your website, do not add http://
linkedin: # Add your Linkedin handle
github: mxklb # Add your Github handle
twitter: # Add your Twitter handle
facebook: # Add your Facebook handle
instagram: # Add your Instagram handle
pinterest: # Add your Pinterest handle

# Newsletter
mailchimp: # Add your MailChimp form identifier.

# Disqus
discus_identifier: # Add your discus identifier

# Tracker
analytics: # Google Analytics

# Paginate
paginate: 6
paginate_path: /page:num/

# Build settings
markdown: kramdown
plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap

include: [_pages]
exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
